/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  NoteMergerModal: () => NoteMergerModal,
  default: () => NoteMergerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var i18n = {
  // Plugin
  pluginName: { zh: "Note Merger", en: "Note Merger" },
  commandName: { zh: "\u5408\u5E76\u7B14\u8BB0", en: "Merge Notes" },
  contextMenu: { zh: "Note Merge", en: "Note Merge" },
  // Modal
  title: { zh: "\u5408\u5E76\u7B14\u8BB0", en: "Merge Notes" },
  searchPlaceholder: { zh: "\u641C\u7D22\u7B14\u8BB0...", en: "Search notes..." },
  selectedTitle: { zh: "\u5DF2\u9009\u7B14\u8BB0\uFF08\u62D6\u52A8\u6392\u5E8F\uFF09", en: "Selected Notes (drag to reorder)" },
  noteNameLabel: { zh: "\u5408\u5E76\u540E\u7B14\u8BB0\u540D\u79F0\uFF1A", en: "Merged note name:" },
  noteNamePlaceholder: { zh: "\u9ED8\u8BA4\uFF1A\u7B2C\u4E00\u4E2A\u6587\u4EF6\u540D_\u5408\u5E76", en: "Default: first filename_merged" },
  targetFolderLabel: { zh: "\u76EE\u6807\u6587\u4EF6\u5939\uFF1A", en: "Target folder:" },
  targetFolderPlaceholder: { zh: "\u9ED8\u8BA4\u4E3A\u5F53\u524D\u6587\u4EF6\u5939", en: "Default: current folder" },
  selectFolder: { zh: "\u9009\u62E9\u6587\u4EF6\u5939", en: "Select folder" },
  deleteSource: { zh: "\u5408\u5E76\u540E\u5220\u9664\u6E90\u7B14\u8BB0\uFF08\u4E0D\u53EF\u64A4\u9500\uFF09", en: "Delete source notes after merge (irreversible)" },
  cancel: { zh: "\u53D6\u6D88", en: "Cancel" },
  merge: { zh: "\u5408\u5E76", en: "Merge" },
  add: { zh: "+", en: "+" },
  remove: { zh: "\xD7", en: "\xD7" },
  // Folder Suggester
  folderTitle: { zh: "\u9009\u62E9\u6587\u4EF6\u5939", en: "Select Folder" },
  folderSearchPlaceholder: { zh: "\u641C\u7D22\u6587\u4EF6\u5939...", en: "Search folders..." },
  select: { zh: "\u9009\u62E9", en: "Select" },
  // Confirm Modal
  confirmTitle: { zh: "\u786E\u8BA4\u5220\u9664", en: "Confirm Delete" },
  confirmMessage: { zh: "\u786E\u5B9A\u8981\u5220\u9664\u6240\u6709\u6E90\u7B14\u8BB0\u5417\uFF1F\u6B64\u64CD\u4F5C\u4E0D\u53EF\u64A4\u9500\u3002", en: "Delete all source notes? This cannot be undone." },
  confirm: { zh: "\u786E\u5B9A", en: "Confirm" },
  // Notices
  noNotesSelected: { zh: "\u8BF7\u5148\u9009\u62E9\u8981\u5408\u5E76\u7684\u7B14\u8BB0", en: "Please select notes to merge" },
  mergeSuccess: { zh: "\u5DF2\u521B\u5EFA\u5408\u5E76\u7B14\u8BB0\uFF1A", en: "Merged note created: " },
  deleteFailed: { zh: "\u5220\u9664\u5931\u8D25\uFF1A", en: "Delete failed: " },
  allDeleted: { zh: "\u5DF2\u5220\u9664\u6240\u6709\u6E90\u7B14\u8BB0", en: "All source notes deleted" },
  mergeFailed: { zh: "\u5408\u5E76\u5931\u8D25\uFF1A", en: "Merge failed: " },
  // Settings
  settingsTitle: { zh: "Note Merger \u8BBE\u7F6E", en: "Note Merger Settings" },
  language: { zh: "\u8BED\u8A00", en: "Language" },
  languageDesc: { zh: "\u9009\u62E9\u63D2\u4EF6\u754C\u9762\u8BED\u8A00", en: "Select plugin interface language" },
  defaultFolder: { zh: "\u9ED8\u8BA4\u6587\u4EF6\u5939", en: "Default Folder" },
  defaultFolderDesc: { zh: "\u5408\u5E76\u540E\u7B14\u8BB0\u7684\u9ED8\u8BA4\u5B58\u653E\u6587\u4EF6\u5939", en: "Default folder for merged notes" },
  defaultFolderPlaceholder: { zh: "\u7559\u7A7A\u4E3A\u5F53\u524D\u6587\u4EF6\u5939", en: "Leave empty for current folder" },
  advancedSettings: { zh: "\u9AD8\u7EA7\u8BBE\u7F6E", en: "Advanced Settings" },
  advancedSettingsDesc: { zh: "\u914D\u7F6E\u5206\u9694\u7B26\u3001\u5220\u9664\u9009\u9879\u7B49", en: "Configure separator, delete options, etc." },
  enter: { zh: "\u8FDB\u5165", en: "Enter" },
  advancedTitle: { zh: "\u9AD8\u7EA7\u8BBE\u7F6E", en: "Advanced Settings" },
  back: { zh: "\u8FD4\u56DE", en: "Back" },
  backDesc: { zh: "\u8FD4\u56DE\u57FA\u672C\u8BBE\u7F6E", en: "Back to basic settings" },
  separator: { zh: "\u5206\u9694\u7B26", en: "Separator" },
  separatorDesc: { zh: "\u5408\u5E76\u7B14\u8BB0\u65F6\u4F7F\u7528\u7684\u5206\u9694\u7B26", en: "Separator used when merging notes" },
  autoDelete: { zh: "\u81EA\u52A8\u5220\u9664\u6E90\u7B14\u8BB0", en: "Auto-delete source notes" },
  autoDeleteDesc: { zh: "\u5408\u5E76\u540E\u81EA\u52A8\u5220\u9664\u6E90\u7B14\u8BB0\uFF08\u5371\u9669\u9009\u9879\uFF09", en: "Auto-delete source notes after merge (dangerous)" }
};
function t(key, lang) {
  var _a, _b;
  return ((_a = i18n[key]) == null ? void 0 : _a[lang]) || ((_b = i18n[key]) == null ? void 0 : _b["zh"]) || key;
}
var DEFAULT_SETTINGS = {
  language: "zh",
  defaultFolder: "",
  separator: "---",
  autoDelete: false,
  hotkey: "Ctrl+M"
};
var NoteMergerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.preSelectedFiles = [];
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "merge-notes",
      name: t("commandName", this.settings.language),
      callback: () => new NoteMergerModal(this.app, this).open()
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        const filesToAdd = [];
        const addedPaths = /* @__PURE__ */ new Set();
        const fileExplorer = this.app.workspace.getLeavesOfType("file-explorer")[0];
        if (fileExplorer) {
          const container = fileExplorer.view.containerEl;
          const selectedItems = container.querySelectorAll(".tree-item-self.is-selected");
          selectedItems.forEach((item) => {
            const path = item.getAttribute("data-path");
            if (path) {
              const tfile = this.app.vault.getAbstractFileByPath(path);
              if (tfile instanceof import_obsidian.TFile && tfile.extension === "md" && !addedPaths.has(path)) {
                filesToAdd.push(tfile);
                addedPaths.add(path);
              }
            }
          });
        }
        if (filesToAdd.length === 0 && file instanceof import_obsidian.TFile && file.extension === "md") {
          filesToAdd.push(file);
        }
        if (filesToAdd.length > 0) {
          menu.addItem((item) => {
            item.setTitle(t("contextMenu", this.settings.language)).setIcon("file-input").onClick(() => {
              this.preSelectedFiles = filesToAdd;
              new NoteMergerModal(this.app, this).open();
            });
          });
        }
      })
    );
    this.addSettingTab(new NoteMergerSettingTab(this.app, this));
  }
  onunload() {
    console.log("Note Merger plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  t(key) {
    return t(key, this.settings.language);
  }
};
var NoteMergerModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.notes = [];
    this.selectedNotes = [];
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("note-merger-modal");
    contentEl.createEl("h2", { text: this.plugin.t("title") });
    const searchContainer = contentEl.createDiv({ cls: "search-container" });
    this.searchInput = searchContainer.createEl("input", {
      type: "text",
      placeholder: this.plugin.t("searchPlaceholder"),
      cls: "search-input"
    });
    this.searchInput.addEventListener("input", () => this.searchNotes());
    this.noteList = contentEl.createDiv({ cls: "note-list" });
    this.loadAllNotes();
    if (this.plugin.preSelectedFiles.length > 0) {
      for (const file of this.plugin.preSelectedFiles) {
        if (!this.selectedNotes.includes(file)) {
          this.selectedNotes.push(file);
        }
      }
      this.plugin.preSelectedFiles = [];
      this.updateMergedNoteName();
    }
    const selectedContainer = contentEl.createDiv({ cls: "selected-container" });
    selectedContainer.createEl("h3", { text: this.plugin.t("selectedTitle") });
    const selectedList = selectedContainer.createDiv({ cls: "selected-list" });
    this.renderSelectedNotes(selectedList);
    const settingsContainer = contentEl.createDiv({ cls: "settings-container" });
    const nameContainer = settingsContainer.createDiv({ cls: "setting-item" });
    nameContainer.createEl("label", { text: this.plugin.t("noteNameLabel") });
    this.mergedNoteName = nameContainer.createEl("input", {
      type: "text",
      placeholder: this.plugin.t("noteNamePlaceholder"),
      cls: "name-input"
    });
    const folderContainer = settingsContainer.createDiv({ cls: "setting-item" });
    folderContainer.createEl("label", { text: this.plugin.t("targetFolderLabel") });
    const folderInputContainer = folderContainer.createDiv({ cls: "folder-input-container" });
    this.targetFolder = folderInputContainer.createEl("input", {
      type: "text",
      placeholder: this.plugin.t("targetFolderPlaceholder"),
      value: this.plugin.settings.defaultFolder,
      cls: "folder-input"
    });
    const folderSelectButton = folderInputContainer.createEl("button", {
      text: this.plugin.t("selectFolder"),
      cls: "folder-select-button"
    });
    folderSelectButton.addEventListener("click", () => {
      new FolderSuggesterModal(this.app, this.plugin, (folder) => {
        this.targetFolder.value = folder.path;
      }).open();
    });
    const deleteContainer = settingsContainer.createDiv({ cls: "setting-item" });
    this.deleteCheckbox = deleteContainer.createEl("input", {
      type: "checkbox",
      cls: "delete-checkbox"
    });
    deleteContainer.createEl("label", { text: this.plugin.t("deleteSource") });
    const buttonContainer = contentEl.createDiv({ cls: "button-container" });
    buttonContainer.createEl("button", { text: this.plugin.t("cancel"), cls: "cancel-button" }).addEventListener("click", () => this.close());
    buttonContainer.createEl("button", { text: this.plugin.t("merge"), cls: "merge-button" }).addEventListener("click", () => this.mergeNotes());
  }
  async loadAllNotes() {
    const files = this.app.vault.getMarkdownFiles();
    this.notes = files.sort((a, b) => b.stat.mtime - a.stat.mtime);
    this.renderNoteList();
  }
  searchNotes() {
    const query = this.searchInput.value.toLowerCase();
    if (!query) {
      this.renderNoteList();
      return;
    }
    const filteredNotes = this.notes.filter(
      (note) => note.name.toLowerCase().includes(query) || note.path.toLowerCase().includes(query)
    );
    this.renderNoteList(filteredNotes);
  }
  renderNoteList(notesToRender) {
    this.noteList.empty();
    const notes = notesToRender || this.notes;
    notes.forEach((note) => {
      const noteItem = this.noteList.createDiv({ cls: "note-item" });
      noteItem.createEl("span", { text: note.name, cls: "note-name" });
      noteItem.createEl("span", { text: note.path, cls: "note-path" });
      const addButton = noteItem.createEl("button", { text: this.plugin.t("add"), cls: "add-button" });
      addButton.addEventListener("click", () => this.addNote(note));
    });
  }
  addNote(note) {
    if (!this.selectedNotes.includes(note)) {
      this.selectedNotes.push(note);
      this.renderSelectedNotes();
      this.updateMergedNoteName();
    }
  }
  removeNote(note) {
    this.selectedNotes = this.selectedNotes.filter((n) => n !== note);
    this.renderSelectedNotes();
    this.updateMergedNoteName();
  }
  renderSelectedNotes(container) {
    var _a;
    const listContainer = container || ((_a = this.noteList.parentElement) == null ? void 0 : _a.querySelector(".selected-list"));
    if (!listContainer)
      return;
    listContainer.empty();
    this.selectedNotes.forEach((note, index) => {
      const noteItem = listContainer.createDiv({
        cls: "selected-note-item"
      });
      noteItem.draggable = true;
      noteItem.dataset.index = index.toString();
      const dragHandle = noteItem.createEl("span", { text: "\u22EE", cls: "drag-handle" });
      noteItem.createEl("span", { text: note.name, cls: "note-name" });
      const removeButton = noteItem.createEl("button", { text: this.plugin.t("remove"), cls: "remove-button" });
      removeButton.addEventListener("click", () => this.removeNote(note));
      noteItem.addEventListener("dragstart", (e) => {
        var _a2;
        (_a2 = e.dataTransfer) == null ? void 0 : _a2.setData("text/plain", index.toString());
        noteItem.addClass("dragging");
      });
      noteItem.addEventListener("dragend", () => {
        noteItem.removeClass("dragging");
      });
      noteItem.addEventListener("dragover", (e) => {
        e.preventDefault();
      });
      noteItem.addEventListener("drop", (e) => {
        var _a2;
        e.preventDefault();
        const fromIndex = parseInt(((_a2 = e.dataTransfer) == null ? void 0 : _a2.getData("text/plain")) || "-1");
        const toIndex = index;
        if (fromIndex !== -1 && fromIndex !== toIndex) {
          const [movedNote] = this.selectedNotes.splice(fromIndex, 1);
          this.selectedNotes.splice(toIndex, 0, movedNote);
          this.renderSelectedNotes();
          this.updateMergedNoteName();
        }
      });
    });
  }
  updateMergedNoteName() {
    if (!this.mergedNoteName.value && this.selectedNotes.length > 0) {
      this.mergedNoteName.placeholder = this.selectedNotes[0].name + "_\u5408\u5E76";
    }
  }
  parseYamlFrontmatter(content) {
    const yamlRegex = /^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/;
    const match = content.match(yamlRegex);
    if (!match) {
      return { frontmatter: null, body: content };
    }
    const yamlContent = match[1];
    const body = match[2];
    const frontmatter = {};
    const lines = yamlContent.split("\n");
    for (const line of lines) {
      const colonIndex = line.indexOf(":");
      if (colonIndex > 0) {
        const key = line.substring(0, colonIndex).trim();
        const value = line.substring(colonIndex + 1).trim();
        if (value.startsWith("[") && value.endsWith("]")) {
          const arrayContent = value.slice(1, -1);
          frontmatter[key] = arrayContent.split(",").map((item) => item.trim());
        } else {
          frontmatter[key] = value;
        }
      }
    }
    return { frontmatter, body };
  }
  mergeYamlFrontmatter(frontmatters) {
    const merged = {};
    const allTags = [];
    for (const frontmatter of frontmatters) {
      if (frontmatter && frontmatter.tags) {
        if (Array.isArray(frontmatter.tags)) {
          allTags.push(...frontmatter.tags);
        } else {
          allTags.push(frontmatter.tags);
        }
      }
    }
    const uniqueTags = [...new Set(allTags)];
    let titleFound = false;
    for (const frontmatter of frontmatters) {
      if (frontmatter && frontmatter.title) {
        merged.title = frontmatter.title;
        titleFound = true;
        break;
      }
    }
    if (!titleFound && frontmatters.length > 0 && frontmatters[0]) {
      Object.assign(merged, frontmatters[0]);
    }
    if (uniqueTags.length > 0) {
      merged.tags = uniqueTags;
    }
    merged.date = new Date().toISOString().split("T")[0];
    return merged;
  }
  frontmatterToString(frontmatter) {
    if (!frontmatter || Object.keys(frontmatter).length === 0) {
      return "";
    }
    let yaml = "---\n";
    for (const [key, value] of Object.entries(frontmatter)) {
      if (Array.isArray(value)) {
        yaml += `${key}: [${value.join(", ")}]
`;
      } else {
        yaml += `${key}: ${value}
`;
      }
    }
    yaml += "---\n";
    return yaml;
  }
  async mergeNotes() {
    if (this.selectedNotes.length === 0) {
      new import_obsidian.Notice(this.plugin.t("noNotesSelected"));
      return;
    }
    const mergedName = this.mergedNoteName.value || this.selectedNotes[0].name + "_\u5408\u5E76";
    const targetPath = this.targetFolder.value;
    const frontmatters = [];
    const bodies = [];
    for (const file of this.selectedNotes) {
      const fileContent = await this.app.vault.read(file);
      const { frontmatter, body } = this.parseYamlFrontmatter(fileContent);
      if (frontmatter) {
        frontmatters.push(frontmatter);
      }
      bodies.push(body);
    }
    const mergedFrontmatter = this.mergeYamlFrontmatter(frontmatters);
    let mergedBody = "";
    for (let i = 0; i < bodies.length; i++) {
      mergedBody += bodies[i].trim();
      if (i < bodies.length - 1) {
        mergedBody += "\n\n" + this.plugin.settings.separator + "\n\n";
      }
    }
    const frontmatterString = this.frontmatterToString(mergedFrontmatter);
    const content = frontmatterString + mergedBody;
    let finalPath = mergedName;
    if (targetPath) {
      finalPath = targetPath + "/" + mergedName;
    }
    if (!finalPath.endsWith(".md")) {
      finalPath += ".md";
    }
    try {
      await this.app.vault.create(finalPath, content);
      new import_obsidian.Notice(this.plugin.t("mergeSuccess") + finalPath);
      if (this.deleteCheckbox.checked) {
        const confirmed = await this.confirmDelete();
        if (confirmed) {
          for (const file of this.selectedNotes) {
            try {
              await this.app.vault.delete(file);
            } catch (error) {
              new import_obsidian.Notice(this.plugin.t("deleteFailed") + file.name);
            }
          }
          new import_obsidian.Notice(this.plugin.t("allDeleted"));
        }
      }
      this.close();
    } catch (error) {
      new import_obsidian.Notice(this.plugin.t("mergeFailed") + error.message);
    }
  }
  async confirmDelete() {
    return new Promise((resolve) => {
      const modal = new ConfirmModal(
        this.app,
        this.plugin,
        this.plugin.t("confirmTitle"),
        this.plugin.t("confirmMessage"),
        resolve
      );
      modal.open();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, plugin, title, message, callback) {
    super(app);
    this.plugin = plugin;
    this.title = title;
    this.message = message;
    this.callback = callback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.title });
    contentEl.createEl("p", { text: this.message });
    const buttonContainer = contentEl.createDiv({ cls: "button-container" });
    buttonContainer.createEl("button", { text: this.plugin.t("cancel"), cls: "cancel-button" }).addEventListener("click", () => {
      this.callback(false);
      this.close();
    });
    buttonContainer.createEl("button", { text: this.plugin.t("confirm"), cls: "confirm-button" }).addEventListener("click", () => {
      this.callback(true);
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var NoteMergerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    const lang = this.plugin.settings.language;
    containerEl.empty();
    containerEl.createEl("h2", { text: this.plugin.t("settingsTitle") });
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("language")).setDesc(this.plugin.t("languageDesc")).addDropdown((dropdown) => dropdown.addOption("zh", "\u4E2D\u6587").addOption("en", "English").setValue(lang).onChange(async (value) => {
      this.plugin.settings.language = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("defaultFolder")).setDesc(this.plugin.t("defaultFolderDesc")).addText((text) => text.setPlaceholder(this.plugin.t("defaultFolderPlaceholder")).setValue(this.plugin.settings.defaultFolder).onChange(async (value) => {
      this.plugin.settings.defaultFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("advancedSettings")).setDesc(this.plugin.t("advancedSettingsDesc")).addButton((button) => button.setButtonText(this.plugin.t("enter")).setCta().onClick(() => {
      this.displayAdvanced();
    }));
  }
  displayAdvanced() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: this.plugin.t("advancedTitle") });
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("back")).setDesc(this.plugin.t("backDesc")).addButton((button) => button.setButtonText(this.plugin.t("back")).setCta().onClick(() => {
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("separator")).setDesc(this.plugin.t("separatorDesc")).addText((text) => text.setValue(this.plugin.settings.separator).onChange(async (value) => {
      this.plugin.settings.separator = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("autoDelete")).setDesc(this.plugin.t("autoDeleteDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.autoDelete).onChange(async (value) => {
      this.plugin.settings.autoDelete = value;
      await this.plugin.saveSettings();
    }));
  }
};
var FolderSuggesterModal = class extends import_obsidian.Modal {
  constructor(app, plugin, callback) {
    super(app);
    this.plugin = plugin;
    this.callback = callback;
    this.folders = this.getAllFolders();
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("folder-suggester-modal");
    contentEl.createEl("h2", { text: this.plugin.t("folderTitle") });
    const searchContainer = contentEl.createDiv({ cls: "search-container" });
    this.searchInput = searchContainer.createEl("input", {
      type: "text",
      placeholder: this.plugin.t("folderSearchPlaceholder"),
      cls: "search-input"
    });
    this.searchInput.addEventListener("input", () => this.searchFolders());
    this.folderList = contentEl.createDiv({ cls: "folder-list" });
    this.renderFolders();
    const buttonContainer = contentEl.createDiv({ cls: "button-container" });
    buttonContainer.createEl("button", { text: this.plugin.t("cancel"), cls: "cancel-button" }).addEventListener("click", () => this.close());
  }
  getAllFolders() {
    const folders = [];
    const root = this.app.vault.getRoot();
    const traverse = (folder) => {
      folders.push(folder);
      folder.children.forEach((child) => {
        if (child instanceof import_obsidian.TFolder) {
          traverse(child);
        }
      });
    };
    traverse(root);
    return folders;
  }
  searchFolders() {
    const query = this.searchInput.value.toLowerCase();
    if (!query) {
      this.renderFolders();
      return;
    }
    const filteredFolders = this.folders.filter(
      (folder) => folder.name.toLowerCase().includes(query) || folder.path.toLowerCase().includes(query)
    );
    this.renderFolders(filteredFolders);
  }
  renderFolders(foldersToRender) {
    this.folderList.empty();
    const folders = foldersToRender || this.folders;
    folders.forEach((folder) => {
      const folderItem = this.folderList.createDiv({ cls: "folder-item" });
      folderItem.createEl("span", { text: folder.name, cls: "folder-name" });
      folderItem.createEl("span", { text: folder.path, cls: "folder-path" });
      const selectButton = folderItem.createEl("button", { text: this.plugin.t("select"), cls: "select-button" });
      selectButton.addEventListener("click", () => {
        this.callback(folder);
        this.close();
      });
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
